<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Syntax highlighting for reStructuredText: http://docutils.sourceforge.net</string>
	<key>fileTypes</key>
	<array>
		<string>rst</string>
		<string>rest</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>reStructuredText</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^([ \t]*)(?=\S)</string>
			<key>contentName</key>
			<string>meta.paragraph.restructuredtext</string>
			<key>end</key>
			<string>^(?!\1)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#all</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>all</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#directives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw-blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#emphasis</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-def</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.substitution.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>substitution</string>
					<key>match</key>
					<string>(\|)[^| ]+[^|]*[^| ]*(\|_{0,2})</string>
					<key>name</key>
					<string>markup.underline.substitution.restructuredtext</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>``</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>inline literal</string>
					<key>end</key>
					<string>``((?=[^`\w\d])|$)</string>
					<key>name</key>
					<string>markup.raw.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.intepreted.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.intepreted.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>intepreted text - single line</string>
					<key>match</key>
					<string>(`)[^`]+(`)(?!_)</string>
					<key>name</key>
					<string>markup.other.command.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>anonymous links __ url</string>
					<key>match</key>
					<string>\s*(__)\s+(.+)</string>
					<key>name</key>
					<string>meta.link.restructuredtext</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-reference</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)([-A-z0-9_.]*)(:)(`)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.intepreted.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.role.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.intepreted.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.intepreted.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>intepreted text - multiline with role</string>
					<key>contentName</key>
					<string>string.other.interpreted.restructuredtext</string>
					<key>end</key>
					<string>(`)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.intepreted.restructuredtext</string>
						</dict>
					</dict>
					<key>name</key>
					<string>markup.other.command.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.location.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.restructuredtext</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.location.restructuredtext</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>links `...`_ </string>
					<key>match</key>
					<string>(`)([^&lt;`]+)\s+(&lt;)(.*?)(&gt;)(`_)</string>
					<key>name</key>
					<string>meta.link.inline.restructuredtext</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#footnotes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#citations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#headings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>citations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.citation.link.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.other.citation.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>replacement</string>
					<key>match</key>
					<string>^(\.\.)\s+((\[)[A-z][A-z0-9]*(\]))(_)\s+(.*)</string>
					<key>name</key>
					<string>meta.link.citation.def.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.citation.link.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>citation reference</string>
					<key>match</key>
					<string>((\[)[A-z][A-z0-9_-]*(\]))(_)</string>
					<key>name</key>
					<string>meta.link.citation.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\.\.)[ ]</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.restructuredtext</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^[\s]*$\n?</string>
					<key>name</key>
					<string>comment.line.double-dot.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^([ \t]*)((\.\.)\sraw(::)) html</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.directive.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>directives.html</string>
					<key>end</key>
					<string>^(?!\1[ \t])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.directive.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>directives</string>
					<key>match</key>
					<string>(\.\.)\s([A-z][-A-z0-9_]+)(::)\s*$</string>
					<key>name</key>
					<string>meta.other.directive.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.directive.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.directive.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>directives with arguments</string>
					<key>match</key>
					<string>(\.\.)\s([A-z][-A-z0-9_]+)(::)\s+(.+?)\s*$</string>
					<key>name</key>
					<string>meta.other.directive.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>emphasis</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\*\*)[^*]+(\*\*)</string>
					<key>name</key>
					<string>markup.bold.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\*)\w[^*]+\w(\*)</string>
					<key>name</key>
					<string>markup.italic.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>footnotes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.footnote.link.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>string.other.footnote.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>replacement</string>
					<key>match</key>
					<string>^(\.\.)\s+((\[)(((#?)[^]]*?)|\*)(\]))\s+(.*)</string>
					<key>name</key>
					<string>meta.link.footnote.def.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.footnote.link</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>footnote reference: [0]_</string>
					<key>match</key>
					<string>((\[)[0-9]+(\]))(_)</string>
					<key>name</key>
					<string>meta.link.footnote.numeric.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.footnote.link</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>footnote reference [#]_ or [#foo]_</string>
					<key>match</key>
					<string>((\[#)[A-z0-9_\-]*(\]))(_)</string>
					<key>name</key>
					<string>meta.link.footnote.auto.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.footnote.link.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>footnote reference [*]_</string>
					<key>match</key>
					<string>((\[)\*(\]))(_)</string>
					<key>name</key>
					<string>meta.link.footnote.symbol.auto.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>headings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^\s*(=|-|~|`|#|"|\^|\+|\*|:|\.|'|_|\+){3,}$){1,1}?</string>
					<key>name</key>
					<string>markup.heading.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>link-def</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.restructuredtext</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>replacement</string>
					<key>match</key>
					<string>(\.\.)\s+(_)([-.\d\w\s()]+)(:)\s+(.*)</string>
					<key>name</key>
					<string>meta.link.reference.def.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.restructuredtext</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>replacement</string>
					<key>match</key>
					<string>(\.\.)\s+(_`)([^`]+)(`:)\s+(.*)</string>
					<key>name</key>
					<string>meta.link.reference.def.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>link-reference</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([-.:+_\d\w]+)(_)\b</string>
					<key>name</key>
					<string>meta.link.reference</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(`)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(`_)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.restructuredtext</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.link.reference</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[^`]+</string>
							<key>name</key>
							<string>string.other.link.title.restructuredtext</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>raw-blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(::)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.raw.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Literal Blocks</string>
					<key>contentName</key>
					<string>meta.raw.block.restructuredtext</string>
					<key>end</key>
					<string>^(?=\S)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#raw-blocks-inner</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>raw-blocks-inner</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>markup.raw.inner.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>tables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.table.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\+-[+-]+</string>
					<key>name</key>
					<string>markup.other.table.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.table.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\+=[+=]+</string>
					<key>name</key>
					<string>markup.other.table.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.field.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.field.restructuredtext</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>tags (and field lists)</string>
					<key>match</key>
					<string>(:)[[:alpha:]][[[:alpha:]]0-9  =\s\t_.-]*(:)</string>
					<key>name</key>
					<string>entity.name.tag.restructuredtext</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.restructuredtext</string>
	<key>uuid</key>
	<string>62DA9AD6-36E1-4AB7-BB87-E933AD9FD1A4</string>
</dict>
</plist>
